### ISSUE TITLE
Is the name of this project appropriate?

### ISSUE THREAD

**Issue by RufusVS** [erdiaker/iomidi#1]
iomidi would indicate to me that this does reading and writing to and from midi devices,
But reading the home page description it seems to be for reading/writing midi files.

**Comment by erdiaker** [comment]
What would you suggest? rwmidi? :)

Sorry for the misunderstanding, but I believe the name is appropriate. It doesn't mention anything about MIDI devices. In fact, the motivation was creating a lightweight library just for MIDI file input/output, without bloating it with playback or device integration.

Also, a device interface can be just a [file](https://en.wikipedia.org/wiki/Everything_is_a_file).
